# Generated by Django 5.2.5 on 2025-08-31 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.CharField(default='A', max_length=10),
        ),
    ]
