# Generated by Django 5.2.5 on 2025-09-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0003_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students_MarK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_marks', models.IntegerField()),
                ('maths_marks', models.IntegerField()),
                ('science_marks', models.IntegerField()),
                ('tamil_marks', models.IntegerField()),
                ('social_marks', models.IntegerField()),
                ('total', models.IntegerField()),
                ('average', models.FloatField()),
                ('score', models.BooleanField()),
            ],
        ),
    ]
