# Generated by Django 5.2.5 on 2025-09-04 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0004_students_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Student_Reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Students.student'),
        ),
    ]
