# Generated by Django 5.2.5 on 2025-09-04 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0005_task_student_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Student_Reference',
            new_name='student_reference',
        ),
    ]
