# Generated by Django 5.2.5 on 2025-09-04 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0006_rename_student_reference_task_student_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='student_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_names', to='Students.student'),
        ),
    ]
